-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."ROLE"
(
    id_role serial NOT NULL,
    label_role character varying(100) COLLATE pg_catalog."default",
    code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id_cursus integer,
    CONSTRAINT "ROLE_pkey" PRIMARY KEY (id_role)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    id_user serial NOT NULL,
    username character varying(255) COLLATE pg_catalog."default",
    password character varying(120) COLLATE pg_catalog."default",
    token character varying(255) COLLATE pg_catalog."default",
    tokentype character varying(50) COLLATE pg_catalog."default",
    revoked boolean,
    expired boolean,
    email character varying(255) COLLATE pg_catalog."default",
    reset_code character varying(255) COLLATE pg_catalog."default",
    verificationtoken_expiration timestamp without time zone,
    reset_code_expiration timestamp without time zone,
    verification_token character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "User_pkey" PRIMARY KEY (id_user),
    CONSTRAINT "User_verification_token_key" UNIQUE (verification_token)
);

CREATE TABLE IF NOT EXISTS public."UserRole"
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT "UserRole_pkey" PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.annee_universitaire
(
    id_annee serial NOT NULL,
    label character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT annee_universitaire_pkey PRIMARY KEY (id_annee)
);

CREATE TABLE IF NOT EXISTS public.audit_log
(
    audit_id serial NOT NULL,
    table_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    record_id text COLLATE pg_catalog."default" NOT NULL,
    operation character varying(10) COLLATE pg_catalog."default" NOT NULL,
    changed_by integer,
    changed_at timestamp without time zone NOT NULL DEFAULT now(),
    old_values jsonb,
    new_values jsonb,
    CONSTRAINT audit_log_pkey PRIMARY KEY (audit_id)
);

CREATE TABLE IF NOT EXISTS public.cursus
(
    id_cursus serial NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cursus_pkey PRIMARY KEY (id_cursus)
);

CREATE TABLE IF NOT EXISTS public.dashboard_metrics_daily
(
    metric_date date NOT NULL,
    nb_diplomes_emis integer NOT NULL,
    nb_diplomes_microservice integer NOT NULL,
    nb_diplomes_upload integer NOT NULL,
    nb_nouveaux_etudiants integer NOT NULL,
    nb_institutions_actives integer NOT NULL,
    nb_diplomes_confirmes integer NOT NULL,
    nb_diplomes_pending integer NOT NULL,
    nb_diplomes_revoques integer NOT NULL,
    nb_verifications integer NOT NULL,
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT dashboard_metrics_daily_pkey PRIMARY KEY (metric_date)
);

CREATE TABLE IF NOT EXISTS public.diplome_blockchain_ext
(
    id_diplome integer NOT NULL,
    titre character varying(255) COLLATE pg_catalog."default",
    mention character varying(50) COLLATE pg_catalog."default",
    date_emission date,
    annee_promotion character varying(20) COLLATE pg_catalog."default",
    hash_sha256 character varying(64) COLLATE pg_catalog."default",
    tx_id_fabric character varying(255) COLLATE pg_catalog."default",
    ipfs_cid character varying(100) COLLATE pg_catalog."default",
    statut statut_diplome DEFAULT 'PENDING_BLOCKCHAIN'::statut_diplome,
    blockchain_retry_count integer,
    blockchain_last_retry timestamp without time zone,
    generation_mode character varying(20) COLLATE pg_catalog."default",
    template_id integer,
    institution_id integer,
    specialite_id character varying(3) COLLATE pg_catalog."default",
    uploaded_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT diplome_blockchain_ext_pkey PRIMARY KEY (id_diplome),
    CONSTRAINT diplome_blockchain_ext_hash_sha256_key UNIQUE (hash_sha256)
);

CREATE TABLE IF NOT EXISTS public.entreprise
(
    id_entreprise serial NOT NULL,
    nom_entreprise character varying(100) COLLATE pg_catalog."default" NOT NULL,
    raison_sociale character varying(255) COLLATE pg_catalog."default",
    matricule_fiscale character varying(15) COLLATE pg_catalog."default",
    secteur_activite character varying(100) COLLATE pg_catalog."default",
    adresse_siege character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(10) COLLATE pg_catalog."default",
    ville character varying(100) COLLATE pg_catalog."default",
    pays character varying(100) COLLATE pg_catalog."default",
    telephone character varying(20) COLLATE pg_catalog."default",
    email_entreprise character varying(100) COLLATE pg_catalog."default",
    site_web character varying(100) COLLATE pg_catalog."default",
    date_creation timestamp without time zone,
    capital_social numeric(15, 2),
    chiffre_affaires numeric(15, 2),
    nombre_employes integer,
    status boolean NOT NULL,
    date_mise_a_jour timestamp without time zone DEFAULT now(),
    description text COLLATE pg_catalog."default",
    CONSTRAINT entreprise_pkey PRIMARY KEY (id_entreprise),
    CONSTRAINT entreprise_matricule_fiscale_key UNIQUE (matricule_fiscale)
);

CREATE TABLE IF NOT EXISTS public.entreprise_auth_sessions
(
    session_id serial NOT NULL,
    entreprise_id integer NOT NULL,
    access_token_jwt text COLLATE pg_catalog."default" NOT NULL,
    tenant_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    microsoft_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    issuer character varying(500) COLLATE pg_catalog."default",
    audience character varying(255) COLLATE pg_catalog."default",
    expires_at timestamp without time zone NOT NULL,
    is_valid boolean NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT entreprise_auth_sessions_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.entreprise_ext
(
    id_entreprise integer NOT NULL,
    siret character varying(20) COLLATE pg_catalog."default",
    microsoft_tenant_id character varying(255) COLLATE pg_catalog."default",
    microsoft_email_domain character varying(255) COLLATE pg_catalog."default",
    statut_validation statut_validation DEFAULT 'EN_ATTENTE'::statut_validation,
    invitation_token character varying(500) COLLATE pg_catalog."default",
    token_expires_at timestamp without time zone,
    valide_par integer,
    date_validation timestamp without time zone,
    CONSTRAINT entreprise_ext_pkey PRIMARY KEY (id_entreprise)
);

CREATE TABLE IF NOT EXISTS public.entreprise_validation_requests
(
    id serial NOT NULL,
    entreprise_id integer NOT NULL,
    ms_tenant_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ms_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    statut statut_validation NOT NULL DEFAULT 'EN_ATTENTE'::statut_validation,
    demande_at timestamp without time zone NOT NULL DEFAULT now(),
    traite_par integer,
    traite_at timestamp without time zone,
    motif_refus text COLLATE pg_catalog."default",
    CONSTRAINT entreprise_validation_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.etudiant
(
    etudiant_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    email_etudiant character varying(100) COLLATE pg_catalog."default",
    nom character varying(100) COLLATE pg_catalog."default",
    date_naissance date,
    num_cin character varying(8) COLLATE pg_catalog."default",
    num_passeport character varying(20) COLLATE pg_catalog."default",
    entreprise_id integer,
    telephone character varying(30) COLLATE pg_catalog."default",
    code_nationalite character varying(3) COLLATE pg_catalog."default",
    code_specialite character varying(3) COLLATE pg_catalog."default",
    date_delivrance date,
    lieu_nais_et character varying(100) COLLATE pg_catalog."default",
    sexe character varying(1) COLLATE pg_catalog."default",
    lieu_delivrance character varying(100) COLLATE pg_catalog."default",
    prenom character varying(100) COLLATE pg_catalog."default",
    id_user integer,
    adresse_postale character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(20) COLLATE pg_catalog."default",
    ville character varying(100) COLLATE pg_catalog."default",
    gouvernorat character varying(100) COLLATE pg_catalog."default",
    linkedin_id character varying(255) COLLATE pg_catalog."default",
    linkedin_url character varying(500) COLLATE pg_catalog."default",
    linkedin_data_id integer,
    email_esprit_etudiant character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT etudiant_pkey PRIMARY KEY (etudiant_id),
    CONSTRAINT etudiant_id_user_key UNIQUE (id_user),
    CONSTRAINT etudiant_linkedin_data_id_key UNIQUE (linkedin_data_id)
);

-- create separate databases for microservices (idempotent)
DO $$
BEGIN
    CREATE DATABASE user_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE institution_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE student_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE diploma_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE document_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE blockchain_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE storage_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE verification_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;
DO $$
BEGIN
    CREATE DATABASE analytics_service_db;
EXCEPTION WHEN duplicate_database THEN
    NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.etudiant_diplome
(
    id_diplome serial NOT NULL,
    etudiant_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    session_diplome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_annexe integer NOT NULL,
    num_diplome integer NOT NULL,
    date_diplome date NOT NULL,
    date_liv_diplome date NOT NULL,
    CONSTRAINT etudiant_diplome_pkey PRIMARY KEY (id_diplome)
);

CREATE TABLE IF NOT EXISTS public.historique_operations
(
    historique_operations_id serial NOT NULL,
    diplome_id integer NOT NULL,
    type_operation type_operation NOT NULL,
    ancien_hash character varying(64) COLLATE pg_catalog."default",
    nouvel_hash character varying(64) COLLATE pg_catalog."default" NOT NULL,
    tx_id_fabric character varying(255) COLLATE pg_catalog."default" NOT NULL,
    acteur_id integer NOT NULL,
    ip_address character varying(45) COLLATE pg_catalog."default",
    ms_tenant_id character varying(255) COLLATE pg_catalog."default",
    commentaire text COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT historique_operations_pkey PRIMARY KEY (historique_operations_id)
);

CREATE TABLE IF NOT EXISTS public.institution
(
    institution_id serial NOT NULL,
    nom_institution character varying(255) COLLATE pg_catalog."default",
    adresse character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(20) COLLATE pg_catalog."default",
    ville character varying(100) COLLATE pg_catalog."default",
    date_creation date,
    pays character varying(100) COLLATE pg_catalog."default",
    telephone character varying(20) COLLATE pg_catalog."default",
    email_institution character varying(100) COLLATE pg_catalog."default",
    site_web character varying(255) COLLATE pg_catalog."default",
    chiffre_affaires numeric(15, 2),
    nombre_employes integer,
    description character varying(255) COLLATE pg_catalog."default",
    id_group_institution integer,
    date_mise_a_jour timestamp without time zone DEFAULT now(),
    CONSTRAINT institution_pkey PRIMARY KEY (institution_id)
);

CREATE TABLE IF NOT EXISTS public.institution_blockchain_ext
(
    institution_id integer NOT NULL,
    channel_id character varying(100) COLLATE pg_catalog."default",
    peer_node_url character varying(255) COLLATE pg_catalog."default",
    status statut_institution NOT NULL DEFAULT 'ACTIVE'::statut_institution,
    code character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT institution_blockchain_ext_pkey PRIMARY KEY (institution_id),
    CONSTRAINT institution_blockchain_ext_channel_id_key UNIQUE (channel_id)
);

CREATE TABLE IF NOT EXISTS public.langue
(
    id_langue serial NOT NULL,
    nom character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT langue_pkey PRIMARY KEY (id_langue)
);

CREATE TABLE IF NOT EXISTS public.linkedin_data
(
    linkedin_data_id serial NOT NULL,
    data jsonb,
    CONSTRAINT linkedin_data_pkey PRIMARY KEY (linkedin_data_id)
);

CREATE TABLE IF NOT EXISTS public.nationalite
(
    code_nationalite character varying(3) COLLATE pg_catalog."default" NOT NULL,
    designation_nationalite character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT nationalite_pkey PRIMARY KEY (code_nationalite)
);

CREATE TABLE IF NOT EXISTS public.qr_code_records
(
    qr_code_records_id serial NOT NULL,
    diplome_id integer NOT NULL,
    etudiant_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    qr_code_path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    identifiant_opaque character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url_verification character varying(500) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT qr_code_records_pkey PRIMARY KEY (qr_code_records_id),
    CONSTRAINT qr_code_records_identifiant_opaque_key UNIQUE (identifiant_opaque)
);

CREATE TABLE IF NOT EXISTS public.rapport
(
    id_rapport serial NOT NULL,
    nom_documents character varying(255) COLLATE pg_catalog."default",
    id_langue integer NOT NULL,
    id_type_impression integer NOT NULL,
    id_annee integer NOT NULL,
    etat boolean,
    code_rapport character varying(25) COLLATE pg_catalog."default",
    CONSTRAINT rapport_pkey PRIMARY KEY (id_rapport),
    CONSTRAINT rapport_code_rapport_key UNIQUE (code_rapport)
);

CREATE TABLE IF NOT EXISTS public.rapport_institution
(
    id_rapport integer NOT NULL,
    institution_id integer NOT NULL,
    CONSTRAINT rapport_institution_pkey PRIMARY KEY (id_rapport, institution_id)
);

CREATE TABLE IF NOT EXISTS public.role_ext
(
    id_role integer NOT NULL,
    description text COLLATE pg_catalog."default",
    permissions text[] COLLATE pg_catalog."default",
    is_active boolean,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT role_ext_pkey PRIMARY KEY (id_role)
);

CREATE TABLE IF NOT EXISTS public.specialite
(
    code_specialite character varying(3) COLLATE pg_catalog."default" NOT NULL,
    designation_specialite character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT specialite_pkey PRIMARY KEY (code_specialite)
);

CREATE TABLE IF NOT EXISTS public.specialite_ext
(
    code_specialite character varying(3) COLLATE pg_catalog."default" NOT NULL,
    nom character varying(200) COLLATE pg_catalog."default",
    code character varying(20) COLLATE pg_catalog."default",
    institution_id integer,
    is_active boolean,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT specialite_ext_pkey PRIMARY KEY (code_specialite)
);

CREATE TABLE IF NOT EXISTS public.template_departement
(
    id uuid NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    departement_id uuid NOT NULL,
    institution_id integer,
    fichier_jrxml_path character varying(500) COLLATE pg_catalog."default",
    fichier_jasper_path character varying(500) COLLATE pg_catalog."default",
    version integer,
    is_active boolean,
    created_by integer,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone,
    CONSTRAINT template_departement_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type_impression
(
    id_type_impression serial NOT NULL,
    nom character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT type_impression_pkey PRIMARY KEY (id_type_impression)
);

CREATE TABLE IF NOT EXISTS public.user_ext
(
    user_id integer NOT NULL,
    statut_diplochain statut_user_diplochain DEFAULT 'EN_ATTENTE'::statut_user_diplochain,
    institution_id integer,
    niveau_acces character varying(50) COLLATE pg_catalog."default",
    microsoft_email character varying(255) COLLATE pg_catalog."default",
    ms_auth_validated_at timestamp without time zone,
    channel_session character varying(255) COLLATE pg_catalog."default",
    blockchain_address character varying(255) COLLATE pg_catalog."default",
    permissions text[] COLLATE pg_catalog."default",
    numero_etudiant character varying(50) COLLATE pg_catalog."default",
    nom character varying(100) COLLATE pg_catalog."default",
    prenom character varying(100) COLLATE pg_catalog."default",
    date_naissance date,
    promotion character varying(100) COLLATE pg_catalog."default",
    entreprise_id integer,
    created_at timestamp without time zone DEFAULT now(),
    last_login timestamp without time zone,
    derniere_action_audit timestamp without time zone,
    CONSTRAINT user_ext_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_role_ext
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    permissions text[] COLLATE pg_catalog."default",
    is_active boolean,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT user_role_ext_pkey PRIMARY KEY (user_id, role_id)
);

ALTER TABLE IF EXISTS public."ROLE"
    ADD CONSTRAINT "ROLE_id_cursus_fkey" FOREIGN KEY (id_cursus)
    REFERENCES public.cursus (id_cursus) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."UserRole"
    ADD CONSTRAINT "UserRole_role_id_fkey" FOREIGN KEY (role_id)
    REFERENCES public."ROLE" (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."UserRole"
    ADD CONSTRAINT "UserRole_user_id_fkey" FOREIGN KEY (user_id)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.audit_log
    ADD CONSTRAINT audit_log_changed_by_fkey FOREIGN KEY (changed_by)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.diplome_blockchain_ext
    ADD CONSTRAINT diplome_blockchain_ext_id_diplome_fkey FOREIGN KEY (id_diplome)
    REFERENCES public.etudiant_diplome (id_diplome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS diplome_blockchain_ext_pkey
    ON public.diplome_blockchain_ext(id_diplome);


ALTER TABLE IF EXISTS public.diplome_blockchain_ext
    ADD CONSTRAINT diplome_blockchain_ext_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.diplome_blockchain_ext
    ADD CONSTRAINT diplome_blockchain_ext_specialite_id_fkey FOREIGN KEY (specialite_id)
    REFERENCES public.specialite (code_specialite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.diplome_blockchain_ext
    ADD CONSTRAINT diplome_blockchain_ext_uploaded_by_fkey FOREIGN KEY (uploaded_by)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public.entreprise_auth_sessions
    ADD CONSTRAINT entreprise_auth_sessions_entreprise_id_fkey FOREIGN KEY (entreprise_id)
    REFERENCES public.entreprise (id_entreprise) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.entreprise_ext
    ADD CONSTRAINT entreprise_ext_id_entreprise_fkey FOREIGN KEY (id_entreprise)
    REFERENCES public.entreprise (id_entreprise) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS entreprise_ext_pkey
    ON public.entreprise_ext(id_entreprise);


ALTER TABLE IF EXISTS public.entreprise_ext
    ADD CONSTRAINT entreprise_ext_valide_par_fkey FOREIGN KEY (valide_par)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.entreprise_validation_requests
    ADD CONSTRAINT entreprise_validation_requests_entreprise_id_fkey FOREIGN KEY (entreprise_id)
    REFERENCES public.entreprise (id_entreprise) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.entreprise_validation_requests
    ADD CONSTRAINT entreprise_validation_requests_traite_par_fkey FOREIGN KEY (traite_par)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.etudiant
    ADD CONSTRAINT etudiant_code_nationalite_fkey FOREIGN KEY (code_nationalite)
    REFERENCES public.nationalite (code_nationalite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.etudiant
    ADD CONSTRAINT etudiant_code_specialite_fkey FOREIGN KEY (code_specialite)
    REFERENCES public.specialite (code_specialite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.etudiant
    ADD CONSTRAINT etudiant_id_user_fkey FOREIGN KEY (id_user)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS etudiant_id_user_key
    ON public.etudiant(id_user);


ALTER TABLE IF EXISTS public.etudiant
    ADD CONSTRAINT etudiant_linkedin_data_id_fkey FOREIGN KEY (linkedin_data_id)
    REFERENCES public.linkedin_data (linkedin_data_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS etudiant_linkedin_data_id_key
    ON public.etudiant(linkedin_data_id);


ALTER TABLE IF EXISTS public.etudiant_diplome
    ADD CONSTRAINT etudiant_diplome_etudiant_id_fkey FOREIGN KEY (etudiant_id)
    REFERENCES public.etudiant (etudiant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historique_operations
    ADD CONSTRAINT historique_operations_acteur_id_fkey FOREIGN KEY (acteur_id)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.historique_operations
    ADD CONSTRAINT historique_operations_diplome_id_fkey FOREIGN KEY (diplome_id)
    REFERENCES public.etudiant_diplome (id_diplome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.institution_blockchain_ext
    ADD CONSTRAINT institution_blockchain_ext_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS institution_blockchain_ext_pkey
    ON public.institution_blockchain_ext(institution_id);


ALTER TABLE IF EXISTS public.qr_code_records
    ADD CONSTRAINT qr_code_records_diplome_id_fkey FOREIGN KEY (diplome_id)
    REFERENCES public.etudiant_diplome (id_diplome) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.qr_code_records
    ADD CONSTRAINT qr_code_records_etudiant_id_fkey FOREIGN KEY (etudiant_id)
    REFERENCES public.etudiant (etudiant_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rapport
    ADD CONSTRAINT rapport_id_annee_fkey FOREIGN KEY (id_annee)
    REFERENCES public.annee_universitaire (id_annee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rapport
    ADD CONSTRAINT rapport_id_langue_fkey FOREIGN KEY (id_langue)
    REFERENCES public.langue (id_langue) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rapport
    ADD CONSTRAINT rapport_id_type_impression_fkey FOREIGN KEY (id_type_impression)
    REFERENCES public.type_impression (id_type_impression) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rapport_institution
    ADD CONSTRAINT rapport_institution_id_rapport_fkey FOREIGN KEY (id_rapport)
    REFERENCES public.rapport (id_rapport) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rapport_institution
    ADD CONSTRAINT rapport_institution_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.role_ext
    ADD CONSTRAINT role_ext_id_role_fkey FOREIGN KEY (id_role)
    REFERENCES public."ROLE" (id_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS role_ext_pkey
    ON public.role_ext(id_role);


ALTER TABLE IF EXISTS public.specialite_ext
    ADD CONSTRAINT specialite_ext_code_specialite_fkey FOREIGN KEY (code_specialite)
    REFERENCES public.specialite (code_specialite) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS specialite_ext_pkey
    ON public.specialite_ext(code_specialite);


ALTER TABLE IF EXISTS public.specialite_ext
    ADD CONSTRAINT specialite_ext_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.template_departement
    ADD CONSTRAINT template_departement_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.template_departement
    ADD CONSTRAINT template_departement_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_ext
    ADD CONSTRAINT user_ext_entreprise_id_fkey FOREIGN KEY (entreprise_id)
    REFERENCES public.entreprise (id_entreprise) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_ext
    ADD CONSTRAINT user_ext_institution_id_fkey FOREIGN KEY (institution_id)
    REFERENCES public.institution (institution_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_ext
    ADD CONSTRAINT user_ext_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public."User" (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_ext_pkey
    ON public.user_ext(user_id);


ALTER TABLE IF EXISTS public.user_role_ext
    ADD CONSTRAINT user_role_ext_user_id_role_id_fkey FOREIGN KEY (user_id, role_id)
    REFERENCES public."UserRole" (user_id, role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_role_ext_pkey
    ON public.user_role_ext(user_id, role_id);

END;